### ISSUE TITLE
Part 2 Checklist

### ISSUE THREAD

**Issue by elisawarner** [elisawarner/Final_Project#3]
- [ ] Create class definition for each row of clinicaltrials.gov search result
- [ ] Create an instance for each row of cached result data
- [ ] Use class definition for packaging scraped information into a dictionary for database
- [ ] Create a __repr__() method
- [ ] Create a __contains__() method
- [ ] Make sure to use class method
