### ISSUE TITLE
Part 3 Checklist

### ISSUE THREAD

**Issue by elisawarner** [elisawarner/Final_Project#4]
- [ ] Accepts results from a list of search terms
- [ ] Goes through the list and finds the corresponding files to the search terms
- [ ] Goes through the corresponding files, adds unique trial status to Status database (consists of "ID" and "Status")
- [ ] Takes status and values in database and creates a dictionary from them. Any new database entries that are recycling a term from "Status" database must use the proper foreign key from dictionary
- [ ] May do same with search terms if time permits.
- [ ] Each database table should have at least 2 columns and end containing at least 4 rows of data (so search terms might not count)
- [ ] There should be at least one relationship between them (aka Status.status --> Study.status_id)
